name = "secretguest"
main = "main.js"
compatibility_date = "2025-08-04"

[[kv_namespaces]]
binding = "sq_adresses"
id = "1df4a493ef51498ba7c3a828ec422c02"

[[kv_namespaces]]
binding = "sq_checked"
id = "c471ea526eb54f139b8b0be93f6a30ba"

[[kv_namespaces]]
binding = "sq-resume"
id = "54797a170ca3405b90972873792ebdcf"

[[kv_namespaces]]
binding = "sq_user_state"
id = "fc25cf85746f4f20a3fc1af8f153940a"

[logs]
level = "info"
enabled = true

[observability.logs]
enabled = true
